openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: sentry-system
          x-walrus-ui:
            group: Basic
            order: 1
        chart_version:
          title: Chart Version
          type: string
          description: The version of the Helm chart.
          default: 5.0.4
          x-walrus-ui:
            group: Basic
            order: 2
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for GlitchTip Helm release.
          default:
            beat:
              limits:
                cpu: 400m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            web:
              limits:
                cpu: 1000m
                memory: 1024Mi
              requests:
                cpu: 500m
                memory: 512Mi
            worker:
              limits:
                cpu: 900m
                memory: 1024Mi
              requests:
                cpu: 450m
                memory: 512Mi
          additionalProperties:
            properties:
              limits:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Limits
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 1
              requests:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Requests
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 2
            required:
            - limits
            - requests
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 3
        secret_key:
          title: Secret Key
          type: string
          description: The secret key for GlitchTip.
          default: default-secret-key
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 4
        database_url:
          title: Database Url
          type: string
          description: Database connection string for GlitchTip.
          default: postgres://default-user:default-pass@localhost:5432/default-db
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 5
        enable_postgres:
          title: Enable Postgres
          type: boolean
          description: Enable postgresql
          default: "false"
          x-walrus-ui:
            group: Basic
            order: 6
        postgres_pass:
          title: Postgres Pass
          type: string
          description: Password for postgres
          default: default-password
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 7
        redis_url:
          title: Redis Url
          type: string
          description: Redis connection string for GlitchTip.
          default: redis://localhost:6379
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        email_url:
          title: Email Url
          type: string
          description: Email URL
          default: smtp://resend:API_KEY@smtp.resend.com:465
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        domain_name:
          title: Domain Name
          type: string
          description: domain name for GlitchTip, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 10
        issuer_name:
          title: Issuer Name
          type: string
          description: 'origin issuer name for annotation cert-manager.io/issuer:'
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 11
        issuer_kind:
          title: Issuer Kind
          type: string
          description: 'origin issuer kind for annotation cert-manager.io/issuer-kind:'
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 12
      x-walrus-ui:
        groupOrder:
        - Basic
